name: Deploy
on: repository_dispatch

jobs:
  deploy:
    name: Deploy to environment
    runs-on: ubuntu-latest
    container: navikt/deployment-cli:0.4.0
    steps:
      - name: On demand deploy
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker pull docker.pkg.github.com/navikt/fpfordel/fpfordel:latest
          echo ::set-env name=IMAGE::docker.pkg.github.com/navikt/fpfordel/fpfordel:latest
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GHA }}
      - name: Deploy til dev-fss t4
        uses: nais/deploy/actions/deploy@v1
        env:
          DRY_RUN: false
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yml
          PRINT_PAYLOAD: true
          VARS: dev-fss-t4.json
